<?php

/**
 * @file
 * Hooks and functionality for druberg
 */

function druberg_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //ksm($form);
}

function druberg_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if (
    !empty($variables['element']['#module']) &&
    $variables['element']['#module'] === 'druberg'
  ) {
    $suggestions[] = $hook . '__' . 'druberg';
  }

  // @todo - can we be sure that its always the first array in ['#submit']?
  if (
    !empty($variables['element']['#submit'][0]) &&
    is_array($variables['element']['#submit'][0]) &&
    in_array('Drupal\druberg\Plugin\Field\FieldWidget\DrubergWidget', $variables['element']['#submit'][0]) &&
    in_array('addMoreSubmit', $variables['element']['#submit'][0])
  ) {
    $suggestions[] = $hook . '__' . 'druberg__addmore';
  }
}

/**
 * Implements hook_theme().
 */
function druberg_theme() {
  return array(
    'druberg' => array(
      'variables' => array('json' => NULL),
      'template' => 'druberg',
    ),
  );
}
